[2023-04-27 22:01:37,316-INFO-dependency-21]: =============== Starting dependency detection ===============
[2023-04-27 22:01:37,316-INFO-getAllFilesFromRepository-43]: Searching all relevant files
[2023-04-27 22:01:37,318-INFO-getDependencies-75]: Searching dependencies...
[2023-04-27 22:01:37,318-INFO-getDependencies-83]: Found requirements.txt
[2023-04-27 22:01:37,319-INFO-getDependencies-92]: Matching regex pattern...
[2023-04-27 22:01:37,319-INFO-dependencyParser-136]: Parsing dependencies...
[2023-04-27 22:01:37,319-INFO-getDependencies-96]: Completed pattern matching for requirements.txt
[2023-04-27 22:01:37,319-ERROR-dependency-40]: Error : TypeError("scanDependencies() missing 1 required positional argument: 'mode'")
[2023-04-27 22:01:37,319-INFO-dependency-42]: Execution time: 0.003259897232055664
[2023-04-27 22:01:37,319-INFO-dependency-43]: =============== Finished dependency detection ===============
[2023-04-27 22:01:42,629-INFO-dependency-21]: =============== Starting dependency detection ===============
[2023-04-27 22:01:42,630-INFO-getAllFilesFromRepository-43]: Searching all relevant files
[2023-04-27 22:01:42,632-INFO-getDependencies-75]: Searching dependencies...
[2023-04-27 22:01:42,633-INFO-getDependencies-83]: Found requirements.txt
[2023-04-27 22:01:42,633-INFO-getDependencies-92]: Matching regex pattern...
[2023-04-27 22:01:42,633-INFO-dependencyParser-136]: Parsing dependencies...
[2023-04-27 22:01:42,633-INFO-getDependencies-96]: Completed pattern matching for requirements.txt
[2023-04-27 22:01:42,633-ERROR-dependency-40]: Error : TypeError("scanDependencies() missing 1 required positional argument: 'mode'")
[2023-04-27 22:01:42,633-INFO-dependency-42]: Execution time: 0.0036118030548095703
[2023-04-27 22:01:42,633-INFO-dependency-43]: =============== Finished dependency detection ===============
[2023-04-27 22:02:01,828-INFO-dependency-21]: =============== Starting dependency detection ===============
[2023-04-27 22:02:01,828-INFO-getAllFilesFromRepository-43]: Searching all relevant files
[2023-04-27 22:02:01,831-INFO-getDependencies-75]: Searching dependencies...
[2023-04-27 22:02:01,831-INFO-getDependencies-83]: Found requirements.txt
[2023-04-27 22:02:01,831-INFO-getDependencies-92]: Matching regex pattern...
[2023-04-27 22:02:01,831-INFO-dependencyParser-136]: Parsing dependencies...
[2023-04-27 22:02:01,831-INFO-getDependencies-96]: Completed pattern matching for requirements.txt
[2023-04-27 22:02:01,831-INFO-scanDependencies-103]: Total dependencies: 33
[2023-04-27 22:02:01,831-INFO-scanDependencies-104]: Scanning dependency vulnerabilities...
[2023-04-27 22:02:02,418-INFO-scanDependency-93]: Scanning argon2 0.1.10...
[2023-04-27 22:02:02,418-INFO-scanDependency-94]: {}
[2023-04-27 22:02:02,930-INFO-scanDependency-93]: Scanning argon2-cffi 21.3.0...
[2023-04-27 22:02:02,930-INFO-scanDependency-94]: {}
[2023-04-27 22:02:03,442-INFO-scanDependency-93]: Scanning argon2-cffi-bindings 21.2.0...
[2023-04-27 22:02:03,443-INFO-scanDependency-94]: {}
[2023-04-27 22:02:04,158-INFO-scanDependency-93]: Scanning asgiref 3.6.0...
[2023-04-27 22:02:04,158-INFO-scanDependency-94]: {}
[2023-04-27 22:02:04,671-INFO-scanDependency-93]: Scanning certifi 2022.12.7...
[2023-04-27 22:02:04,671-INFO-scanDependency-94]: {}
[2023-04-27 22:02:05,184-INFO-scanDependency-93]: Scanning cffi 1.15.1...
[2023-04-27 22:02:05,184-INFO-scanDependency-94]: {}
[2023-04-27 22:02:05,695-INFO-scanDependency-93]: Scanning charset-normalizer 3.0.1...
[2023-04-27 22:02:05,695-INFO-scanDependency-94]: {}
[2023-04-27 22:02:06,208-INFO-scanDependency-93]: Scanning cryptography 39.0.1...
[2023-04-27 22:02:06,208-INFO-scanDependency-94]: {}
[2023-04-27 22:02:06,719-INFO-scanDependency-93]: Scanning defusedxml 0.7.1...
[2023-04-27 22:02:06,719-INFO-scanDependency-94]: {}
[2023-04-27 22:02:07,199-INFO-scanDependency-93]: Scanning dj-database-url 0.5.0...
[2023-04-27 22:02:07,199-INFO-scanDependency-94]: {}
[2023-04-27 22:02:07,660-INFO-scanDependency-93]: Scanning Django 4.1.7...
[2023-04-27 22:02:07,661-INFO-scanDependency-94]: {}
[2023-04-27 22:02:08,154-INFO-scanDependency-93]: Scanning django-allauth 0.52.0...
[2023-04-27 22:02:08,154-INFO-scanDependency-94]: {}
[2023-04-27 22:02:08,650-INFO-scanDependency-93]: Scanning django-crispy-forms 2.0...
[2023-04-27 22:02:08,651-INFO-scanDependency-94]: {}
[2023-04-27 22:02:09,231-INFO-scanDependency-93]: Scanning django-heroku 0.3.1...
[2023-04-27 22:02:09,232-INFO-scanDependency-94]: {}
[2023-04-27 22:02:09,791-INFO-scanDependency-93]: Scanning idna 3.4...
[2023-04-27 22:02:09,791-INFO-scanDependency-94]: {}
[2023-04-27 22:02:10,305-INFO-scanDependency-93]: Scanning mccabe 0.6.1...
[2023-04-27 22:02:10,305-INFO-scanDependency-94]: {}
[2023-04-27 22:02:10,770-INFO-scanDependency-93]: Scanning oauthlib 3.2.2...
[2023-04-27 22:02:10,770-INFO-scanDependency-94]: {}
[2023-04-27 22:02:11,327-INFO-scanDependency-93]: Scanning Pillow 9.4.0...
[2023-04-27 22:02:11,327-INFO-scanDependency-94]: {}
[2023-04-27 22:02:11,839-INFO-scanDependency-93]: Scanning psycopg2 2.9.3...
[2023-04-27 22:02:11,839-INFO-scanDependency-94]: {}
[2023-04-27 22:02:12,351-INFO-scanDependency-93]: Scanning pycodestyle 2.7.0...
[2023-04-27 22:02:12,351-INFO-scanDependency-94]: {}
[2023-04-27 22:02:12,863-INFO-scanDependency-93]: Scanning pycparser 2.21...
[2023-04-27 22:02:12,863-INFO-scanDependency-94]: {}
[2023-04-27 22:02:13,375-INFO-scanDependency-93]: Scanning pyflakes 2.3.1...
[2023-04-27 22:02:13,376-INFO-scanDependency-94]: {}
[2023-04-27 22:02:13,990-INFO-scanDependency-93]: Scanning PyJWT 2.4.0...
[2023-04-27 22:02:13,991-INFO-scanDependency-94]: {}
[2023-04-27 22:02:14,502-INFO-scanDependency-93]: Scanning python3-openid 3.2.0...
[2023-04-27 22:02:14,502-INFO-scanDependency-94]: {}
[2023-04-27 22:02:15,015-INFO-scanDependency-93]: Scanning pytz 2020.1...
[2023-04-27 22:02:15,016-INFO-scanDependency-94]: {}
[2023-04-27 22:02:15,648-INFO-scanDependency-93]: Scanning PyYAML 5.1...
[2023-04-27 22:02:15,648-INFO-scanDependency-94]: {'vulns': [{'id': 'GHSA-3pqx-4fqf-j49f', 'summary': 'Deserialization of Untrusted Data in PyYAML', 'details': 'PyYAML 5.1 through 5.1.2 has insufficient restrictions on the load and load_all functions because of a class deserialization issue, e.g., Popen is a class in the subprocess module. NOTE: this issue exists because of an incomplete fix for CVE-2017-18342.', 'aliases': ['CVE-2019-20477'], 'modified': '2023-04-11T01:26:59.015905Z', 'published': '2021-04-20T16:40:42Z', 'database_specific': {'cwe_ids': ['CWE-502'], 'severity': 'HIGH', 'github_reviewed': True, 'github_reviewed_at': '2021-04-08T19:24:04Z', 'nvd_published_at': '2020-02-19T04:15:00Z'}, 'references': [{'type': 'ADVISORY', 'url': 'https://nvd.nist.gov/vuln/detail/CVE-2019-20477'}, {'type': 'PACKAGE', 'url': 'https://github.com/yaml/pyyaml'}, {'type': 'WEB', 'url': 'https://github.com/yaml/pyyaml/blob/master/CHANGES'}, {'type': 'WEB', 'url': 'https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/33VBUY73AA6CTTYL3LRWHNFDULV7PFPN/'}, {'type': 'WEB', 'url': 'https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/52N5XS73Z5S4ZN7I7R56ICCPCTKCUV4H/'}, {'type': 'WEB', 'url': 'https://www.exploit-db.com/download/47655'}], 'affected': [{'package': {'name': 'pyyaml', 'ecosystem': 'PyPI', 'purl': 'pkg:pypi/pyyaml'}, 'ranges': [{'type': 'ECOSYSTEM', 'events': [{'introduced': '5.1'}, {'fixed': '5.2'}]}], 'versions': ['5.1', '5.1.1', '5.1.2', '5.2b1'], 'database_specific': {'source': 'https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2021/04/GHSA-3pqx-4fqf-j49f/GHSA-3pqx-4fqf-j49f.json'}}], 'schema_version': '1.4.0', 'severity': [{'type': 'CVSS_V3', 'score': 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H'}]}, {'id': 'GHSA-6757-jp84-gxfx', 'summary': 'Improper Input Validation in PyYAML', 'details': 'A vulnerability was discovered in the PyYAML library in versions before 5.3.1, where it is susceptible to arbitrary code execution when it processes untrusted YAML files through the full_load method or with the FullLoader loader. Applications that use the library to process untrusted input may be vulnerable to this flaw. An attacker could use this flaw to execute arbitrary code on the system by abusing the python/object/new constructor.', 'aliases': ['CVE-2020-1747'], 'modified': '2023-04-17T21:48:09.993850Z', 'published': '2021-04-20T16:14:24Z', 'database_specific': {'cwe_ids': ['CWE-20'], 'severity': 'CRITICAL', 'github_reviewed': True, 'github_reviewed_at': '2021-04-07T22:29:00Z', 'nvd_published_at': '2020-03-24T15:15:00Z'}, 'references': [{'type': 'ADVISORY', 'url': 'https://nvd.nist.gov/vuln/detail/CVE-2020-1747'}, {'type': 'WEB', 'url': 'https://github.com/yaml/pyyaml/pull/386'}, {'type': 'WEB', 'url': 'https://github.com/yaml/pyyaml/commit/5080ba513377b6355a0502104846ee804656f1e0'}, {'type': 'WEB', 'url': 'https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2020-1747'}, {'type': 'PACKAGE', 'url': 'https://github.com/yaml/pyyaml'}, {'type': 'WEB', 'url': 'https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/7PPAS6C4SZRDQLR7C22A5U3QOLXY33JX/'}, {'type': 'WEB', 'url': 'https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/K5HEPD7LEVDPCITY5IMDYWXUMX37VFMY/'}, {'type': 'WEB', 'url': 'https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/MMQXSZXNJT6ERABJZAAICI3DQSQLCP3D/'}, {'type': 'WEB', 'url': 'https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/WORRFHPQVAFKKXXWLSSW6XKUYLWM6CSH/'}, {'type': 'WEB', 'url': 'https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ZBJA3SGNJKCAYPSHOHWY3KBCWNM5NYK2/'}, {'type': 'WEB', 'url': 'https://www.oracle.com/security-alerts/cpujul2022.html'}, {'type': 'WEB', 'url': 'http://lists.opensuse.org/opensuse-security-announce/2020-04/msg00017.html'}, {'type': 'WEB', 'url': 'http://lists.opensuse.org/opensuse-security-announce/2020-05/msg00017.html'}], 'affected': [{'package': {'name': 'pyyaml', 'ecosystem': 'PyPI', 'purl': 'pkg:pypi/pyyaml'}, 'ranges': [{'type': 'ECOSYSTEM', 'events': [{'introduced': '0'}, {'fixed': '5.3.1'}]}], 'versions': ['3.01', '3.02', '3.03', '3.04', '3.05', '3.06', '3.07', '3.08', '3.09', '3.10', '3.11', '3.12', '3.13', '3.13b1', '3.13rc1', '4.2b1', '4.2b2', '4.2b4', '5.1', '5.1.1', '5.1.2', '5.1b1', '5.1b3', '5.1b5', '5.1b7', '5.2', '5.2b1', '5.3', '5.3b1'], 'ecosystem_specific': {'affected_functions': ['lib.yaml.constructor.BaseConstructor.check_state_key', 'lib.yaml.constructor.FullConstructor.get_state_keys_blacklist', 'lib.yaml.constructor.FullConstructor.get_state_keys_blacklist_regexp', 'lib.yaml.constructor.FullConstructor.set_python_instance_state', 'lib.yaml.constructor.UnsafeConstructor.set_python_instance_state']}, 'database_specific': {'source': 'https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2021/04/GHSA-6757-jp84-gxfx/GHSA-6757-jp84-gxfx.json'}}], 'schema_version': '1.4.0', 'severity': [{'type': 'CVSS_V3', 'score': 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H'}]}, {'id': 'GHSA-8q59-q68h-6hv4', 'summary': 'Improper Input Validation in PyYAML', 'details': 'A vulnerability was discovered in the PyYAML library in versions before 5.4, where it is susceptible to arbitrary code execution when it processes untrusted YAML files through the full_load method or with the FullLoader loader. Applications that use the library to process untrusted input may be vulnerable to this flaw. This flaw allows an attacker to execute arbitrary code on the system by abusing the python/object/new constructor. This flaw is due to an incomplete fix for CVE-2020-1747.', 'aliases': ['CVE-2020-14343'], 'modified': '2023-04-11T01:48:33.682381Z', 'published': '2021-03-25T21:26:26Z', 'database_specific': {'cwe_ids': ['CWE-20'], 'severity': 'CRITICAL', 'github_reviewed': True, 'github_reviewed_at': '2021-03-25T21:15:23Z', 'nvd_published_at': '2021-02-09T21:15:00Z'}, 'references': [{'type': 'ADVISORY', 'url': 'https://nvd.nist.gov/vuln/detail/CVE-2020-14343'}, {'type': 'WEB', 'url': 'https://github.com/yaml/pyyaml/issues/420#issuecomment-663673966'}, {'type': 'WEB', 'url': 'https://github.com/yaml/pyyaml/commit/a001f2782501ad2d24986959f0239a354675f9dc'}, {'type': 'WEB', 'url': 'https://bugzilla.redhat.com/show_bug.cgi?id=1860466'}, {'type': 'PACKAGE', 'url': 'https://github.com/yaml/pyyaml'}, {'type': 'WEB', 'url': 'https://pypi.org/project/PyYAML/'}, {'type': 'WEB', 'url': 'https://www.oracle.com/security-alerts/cpuapr2022.html'}, {'type': 'WEB', 'url': 'https://www.oracle.com/security-alerts/cpujul2022.html'}], 'affected': [{'package': {'name': 'pyyaml', 'ecosystem': 'PyPI', 'purl': 'pkg:pypi/pyyaml'}, 'ranges': [{'type': 'ECOSYSTEM', 'events': [{'introduced': '0'}, {'fixed': '5.4'}]}], 'versions': ['3.01', '3.02', '3.03', '3.04', '3.05', '3.06', '3.07', '3.08', '3.09', '3.10', '3.11', '3.12', '3.13', '3.13b1', '3.13rc1', '4.2b1', '4.2b2', '4.2b4', '5.1', '5.1.1', '5.1.2', '5.1b1', '5.1b3', '5.1b5', '5.1b7', '5.2', '5.2b1', '5.3', '5.3.1', '5.3b1', '5.4b1', '5.4b2'], 'ecosystem_specific': {'affected_functions': ['yaml.constructor.FullConstructor', 'yaml.constructor.UnsafeConstructor']}, 'database_specific': {'source': 'https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2021/03/GHSA-8q59-q68h-6hv4/GHSA-8q59-q68h-6hv4.json'}}], 'schema_version': '1.4.0', 'severity': [{'type': 'CVSS_V3', 'score': 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H'}]}, {'id': 'PYSEC-2020-176', 'details': 'PyYAML 5.1 through 5.1.2 has insufficient restrictions on the load and load_all functions because of a class deserialization issue, e.g., Popen is a class in the subprocess module. NOTE: this issue exists because of an incomplete fix for CVE-2017-18342.', 'aliases': ['CVE-2019-20477', 'GHSA-3pqx-4fqf-j49f'], 'modified': '2020-03-01T00:15:00Z', 'published': '2020-02-19T04:15:00Z', 'references': [{'type': 'WEB', 'url': 'https://www.exploit-db.com/download/47655'}, {'type': 'WEB', 'url': 'https://github.com/yaml/pyyaml/blob/master/CHANGES'}, {'type': 'WEB', 'url': 'https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/52N5XS73Z5S4ZN7I7R56ICCPCTKCUV4H/'}, {'type': 'WEB', 'url': 'https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/33VBUY73AA6CTTYL3LRWHNFDULV7PFPN/'}, {'type': 'ADVISORY', 'url': 'https://github.com/advisories/GHSA-3pqx-4fqf-j49f'}], 'affected': [{'package': {'name': 'pyyaml', 'ecosystem': 'PyPI', 'purl': 'pkg:pypi/pyyaml'}, 'ranges': [{'type': 'ECOSYSTEM', 'events': [{'introduced': '5.1'}, {'fixed': '5.2b1'}]}], 'versions': ['5.1', '5.1.1', '5.1.2'], 'database_specific': {'source': 'https://github.com/pypa/advisory-database/blob/main/vulns/pyyaml/PYSEC-2020-176.yaml'}}], 'schema_version': '1.4.0'}, {'id': 'PYSEC-2020-96', 'details': 'A vulnerability was discovered in the PyYAML library in versions before 5.3.1, where it is susceptible to arbitrary code execution when it processes untrusted YAML files through the full_load method or with the FullLoader loader. Applications that use the library to process untrusted input may be vulnerable to this flaw. An attacker could use this flaw to execute arbitrary code on the system by abusing the python/object/new constructor.', 'aliases': ['CVE-2020-1747', 'GHSA-6757-jp84-gxfx'], 'modified': '2021-03-26T02:44:00Z', 'published': '2020-03-24T15:15:00Z', 'references': [{'type': 'REPORT', 'url': 'https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2020-1747'}, {'type': 'WEB', 'url': 'https://github.com/yaml/pyyaml/pull/386'}, {'type': 'WEB', 'url': 'https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/WORRFHPQVAFKKXXWLSSW6XKUYLWM6CSH/'}, {'type': 'WEB', 'url': 'https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ZBJA3SGNJKCAYPSHOHWY3KBCWNM5NYK2/'}, {'type': 'WEB', 'url': 'https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/K5HEPD7LEVDPCITY5IMDYWXUMX37VFMY/'}, {'type': 'WEB', 'url': 'http://lists.opensuse.org/opensuse-security-announce/2020-04/msg00017.html'}, {'type': 'WEB', 'url': 'http://lists.opensuse.org/opensuse-security-announce/2020-05/msg00017.html'}, {'type': 'WEB', 'url': 'https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/MMQXSZXNJT6ERABJZAAICI3DQSQLCP3D/'}, {'type': 'WEB', 'url': 'https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/7PPAS6C4SZRDQLR7C22A5U3QOLXY33JX/'}, {'type': 'ADVISORY', 'url': 'https://github.com/advisories/GHSA-6757-jp84-gxfx'}], 'affected': [{'package': {'name': 'pyyaml', 'ecosystem': 'PyPI', 'purl': 'pkg:pypi/pyyaml'}, 'ranges': [{'type': 'ECOSYSTEM', 'events': [{'introduced': '5.1'}, {'fixed': '5.3.1'}]}], 'versions': ['5.1', '5.1.1', '5.1.2', '5.2b1', '5.2', '5.3b1', '5.3'], 'database_specific': {'source': 'https://github.com/pypa/advisory-database/blob/main/vulns/pyyaml/PYSEC-2020-96.yaml'}}], 'schema_version': '1.4.0'}, {'id': 'PYSEC-2021-142', 'details': 'A vulnerability was discovered in the PyYAML library in versions before 5.4, where it is susceptible to arbitrary code execution when it processes untrusted YAML files through the full_load method or with the FullLoader loader. Applications that use the library to process untrusted input may be vulnerable to this flaw. This flaw allows an attacker to execute arbitrary code on the system by abusing the python/object/new constructor. This flaw is due to an incomplete fix for CVE-2020-1747.', 'aliases': ['CVE-2020-14343', 'GHSA-8q59-q68h-6hv4'], 'modified': '2021-08-27T03:22:18.913334Z', 'published': '2021-02-09T21:15:00Z', 'references': [{'type': 'REPORT', 'url': 'https://bugzilla.redhat.com/show_bug.cgi?id=1860466'}, {'type': 'ADVISORY', 'url': 'https://github.com/advisories/GHSA-8q59-q68h-6hv4'}], 'affected': [{'package': {'name': 'pyyaml', 'ecosystem': 'PyPI', 'purl': 'pkg:pypi/pyyaml'}, 'ranges': [{'type': 'ECOSYSTEM', 'events': [{'introduced': '0'}, {'fixed': '5.4'}]}], 'versions': ['3.01', '3.02', '3.03', '3.04', '3.05', '3.06', '3.07', '3.08', '3.09', '3.10', '3.11', '3.12', '3.13', '3.13b1', '3.13rc1', '4.2b1', '4.2b2', '4.2b4', '5.1', '5.1.1', '5.1.2', '5.1b1', '5.1b3', '5.1b5', '5.1b7', '5.2', '5.2b1', '5.3', '5.3.1', '5.3b1', '5.4b1', '5.4b2'], 'database_specific': {'source': 'https://github.com/pypa/advisory-database/blob/main/vulns/pyyaml/PYSEC-2021-142.yaml'}}], 'schema_version': '1.4.0'}]}
[2023-04-27 22:02:16,140-INFO-scanDependency-93]: Scanning requests 2.28.2...
[2023-04-27 22:02:16,140-INFO-scanDependency-94]: {}
[2023-04-27 22:02:16,652-INFO-scanDependency-93]: Scanning requests-oauthlib 1.3.1...
[2023-04-27 22:02:16,652-INFO-scanDependency-94]: {}
[2023-04-27 22:02:17,173-INFO-scanDependency-93]: Scanning sqlparse 0.3.1...
[2023-04-27 22:02:17,173-INFO-scanDependency-94]: {'vulns': [{'id': 'GHSA-rrm6-wvj7-cwh2', 'summary': 'sqlparse contains a regular expression that is vulnerable to Regular Expression Denial of Service', 'details': '### Impact\nThe SQL parser contains a regular expression that is vulnerable to [ReDoS](https://owasp.org/www-community/attacks/Regular_expression_Denial_of_Service_-_ReDoS) (Regular Expression Denial of Service). The vulnerability may lead to Denial of Service (DoS).\n\n### Patches\nThis issues has been fixed in sqlparse 0.4.4.\n\n### Workarounds\nNone. \n\n### References\nThis issue was discovered and reported by GHSL team member [@erik-krogh (Erik Krogh Kristensen)](https://github.com/erik-krogh).\n- Commit that introduced the vulnerability: e75e35869473832a1eb67772b1adfee2db11b85a\n', 'aliases': ['CVE-2023-30608'], 'modified': '2023-04-21T20:31:59.337711Z', 'published': '2023-04-21T20:24:21Z', 'database_specific': {'cwe_ids': ['CWE-1333'], 'severity': 'MODERATE', 'github_reviewed': True, 'github_reviewed_at': '2023-04-21T20:24:21Z', 'nvd_published_at': None}, 'references': [{'type': 'WEB', 'url': 'https://github.com/andialbrecht/sqlparse/security/advisories/GHSA-rrm6-wvj7-cwh2'}, {'type': 'ADVISORY', 'url': 'https://nvd.nist.gov/vuln/detail/CVE-2023-30608'}, {'type': 'WEB', 'url': 'https://github.com/andialbrecht/sqlparse/commit/c457abd5f097dd13fb21543381e7cfafe7d31cfb'}, {'type': 'WEB', 'url': 'https://github.com/andialbrecht/sqlparse/commit/e75e35869473832a1eb67772b1adfee2db11b85a'}, {'type': 'PACKAGE', 'url': 'https://github.com/andialbrecht/sqlparse'}, {'type': 'WEB', 'url': 'https://owasp.org/www-community/attacks/Regular_expression_Denial_of_Service_-_ReDoS'}], 'affected': [{'package': {'name': 'sqlparse', 'ecosystem': 'PyPI', 'purl': 'pkg:pypi/sqlparse'}, 'ranges': [{'type': 'ECOSYSTEM', 'events': [{'introduced': '0.1.15'}, {'fixed': '0.4.4'}]}], 'versions': ['0.1.15', '0.1.16', '0.1.17', '0.1.18', '0.1.19', '0.2.0', '0.2.1', '0.2.2', '0.2.3', '0.2.4', '0.3.0', '0.3.1', '0.4.0', '0.4.1', '0.4.2', '0.4.3'], 'ecosystem_specific': {'affected_functions': ['sqlparse.keywords.SQL_REGEX', 'sqlparse.lexer.Lexer']}, 'database_specific': {'source': 'https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2023/04/GHSA-rrm6-wvj7-cwh2/GHSA-rrm6-wvj7-cwh2.json'}}], 'schema_version': '1.4.0', 'severity': [{'type': 'CVSS_V3', 'score': 'CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H'}]}]}
[2023-04-27 22:02:17,677-INFO-scanDependency-93]: Scanning urllib3 1.26.9...
[2023-04-27 22:02:17,678-INFO-scanDependency-94]: {}
[2023-04-27 22:02:18,209-INFO-scanDependency-93]: Scanning Werkzeug 2.1.2...
[2023-04-27 22:02:18,209-INFO-scanDependency-94]: {'vulns': [{'id': 'GHSA-px8h-6qxv-m22q', 'summary': 'Incorrect parsing of nameless cookies leads to __Host- cookies bypass', 'details': 'Browsers may allow "nameless" cookies that look like `=value` instead of `key=value`. A vulnerable browser may allow a compromised application on an adjacent subdomain to exploit this to set a cookie like `=__Host-test=bad` for another subdomain.\n\nWerkzeug <= 2.2.2 will parse the cookie `=__Host-test=bad` as `__Host-test=bad`. If a Werkzeug application is running next to a vulnerable or malicious subdomain which sets such a cookie using a vulnerable browser, the Werkzeug application will see the bad cookie value but the valid cookie key.', 'aliases': ['CVE-2023-23934'], 'modified': '2023-04-11T01:48:25.804041Z', 'published': '2023-02-15T15:37:03Z', 'database_specific': {'cwe_ids': [], 'severity': 'LOW', 'github_reviewed': True, 'github_reviewed_at': '2023-02-15T15:37:03Z', 'nvd_published_at': '2023-02-14T20:15:00Z'}, 'references': [{'type': 'WEB', 'url': 'https://github.com/pallets/werkzeug/security/advisories/GHSA-px8h-6qxv-m22q'}, {'type': 'ADVISORY', 'url': 'https://nvd.nist.gov/vuln/detail/CVE-2023-23934'}, {'type': 'WEB', 'url': 'https://github.com/pallets/werkzeug/commit/cf275f42acad1b5950c50ffe8ef58fe62cdce028'}, {'type': 'PACKAGE', 'url': 'https://github.com/pallets/werkzeug'}, {'type': 'WEB', 'url': 'https://github.com/pallets/werkzeug/releases/tag/2.2.3'}], 'affected': [{'package': {'name': 'werkzeug', 'ecosystem': 'PyPI', 'purl': 'pkg:pypi/werkzeug'}, 'ranges': [{'type': 'ECOSYSTEM', 'events': [{'introduced': '0'}, {'fixed': '2.2.3'}]}], 'versions': ['0.1', '0.10', '0.10.1', '0.10.2', '0.10.3', '0.10.4', '0.11', '0.11.1', '0.11.10', '0.11.11', '0.11.12', '0.11.13', '0.11.14', '0.11.15', '0.11.2', '0.11.3', '0.11.4', '0.11.5', '0.11.6', '0.11.7', '0.11.8', '0.11.9', '0.12', '0.12.1', '0.12.2', '0.13', '0.14', '0.14.1', '0.15.0', '0.15.1', '0.15.2', '0.15.3', '0.15.4', '0.15.5', '0.15.6', '0.16.0', '0.16.1', '0.2', '0.3', '0.3.1', '0.4', '0.4.1', '0.5', '0.5.1', '0.6', '0.6.1', '0.6.2', '0.7', '0.7.1', '0.7.2', '0.8', '0.8.1', '0.8.2', '0.8.3', '0.9', '0.9.1', '0.9.2', '0.9.3', '0.9.4', '0.9.5', '0.9.6', '1.0.0', '1.0.0rc1', '1.0.1', '2.0.0', '2.0.0rc1', '2.0.0rc2', '2.0.0rc3', '2.0.0rc4', '2.0.0rc5', '2.0.1', '2.0.2', '2.0.3', '2.1.0', '2.1.1', '2.1.2', '2.2.0', '2.2.0a1', '2.2.1', '2.2.2'], 'database_specific': {'source': 'https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2023/02/GHSA-px8h-6qxv-m22q/GHSA-px8h-6qxv-m22q.json'}}], 'schema_version': '1.4.0', 'severity': [{'type': 'CVSS_V3', 'score': 'CVSS:3.1/AV:A/AC:H/PR:N/UI:R/S:U/C:N/I:L/A:N'}]}, {'id': 'GHSA-xg9f-g7g7-2323', 'summary': 'High resource usage when parsing multipart form data with many fields', 'details': "Werkzeug's multipart form data parser will parse an unlimited number of parts, including file parts. Parts can be a small amount of bytes, but each requires CPU time to parse and may use more memory as Python data. If a request can be made to an endpoint that accesses `request.data`, `request.form`, `request.files`, or `request.get_data(parse_form_data=False)`, it can cause unexpectedly high resource usage.\n\nThis allows an attacker to cause a denial of service by sending crafted multipart data to an endpoint that will parse it. The amount of CPU time required can block worker processes from handling legitimate requests. The amount of RAM required can trigger an out of memory kill of the process. Unlimited file parts can use up memory and file handles. If many concurrent requests are sent continuously, this can exhaust or kill all available workers.", 'aliases': ['CVE-2023-25577'], 'modified': '2023-04-11T01:18:51.835564Z', 'published': '2023-02-15T15:36:26Z', 'database_specific': {'cwe_ids': ['CWE-400', 'CWE-770'], 'severity': 'HIGH', 'github_reviewed': True, 'github_reviewed_at': '2023-02-15T15:36:26Z', 'nvd_published_at': '2023-02-14T20:15:00Z'}, 'references': [{'type': 'WEB', 'url': 'https://github.com/pallets/werkzeug/security/advisories/GHSA-xg9f-g7g7-2323'}, {'type': 'ADVISORY', 'url': 'https://nvd.nist.gov/vuln/detail/CVE-2023-25577'}, {'type': 'WEB', 'url': 'https://github.com/pallets/werkzeug/commit/517cac5a804e8c4dc4ed038bb20dacd038e7a9f1'}, {'type': 'PACKAGE', 'url': 'https://github.com/pallets/werkzeug'}, {'type': 'WEB', 'url': 'https://github.com/pallets/werkzeug/releases/tag/2.2.3'}], 'affected': [{'package': {'name': 'werkzeug', 'ecosystem': 'PyPI', 'purl': 'pkg:pypi/werkzeug'}, 'ranges': [{'type': 'ECOSYSTEM', 'events': [{'introduced': '0'}, {'fixed': '2.2.3'}]}], 'versions': ['0.1', '0.10', '0.10.1', '0.10.2', '0.10.3', '0.10.4', '0.11', '0.11.1', '0.11.10', '0.11.11', '0.11.12', '0.11.13', '0.11.14', '0.11.15', '0.11.2', '0.11.3', '0.11.4', '0.11.5', '0.11.6', '0.11.7', '0.11.8', '0.11.9', '0.12', '0.12.1', '0.12.2', '0.13', '0.14', '0.14.1', '0.15.0', '0.15.1', '0.15.2', '0.15.3', '0.15.4', '0.15.5', '0.15.6', '0.16.0', '0.16.1', '0.2', '0.3', '0.3.1', '0.4', '0.4.1', '0.5', '0.5.1', '0.6', '0.6.1', '0.6.2', '0.7', '0.7.1', '0.7.2', '0.8', '0.8.1', '0.8.2', '0.8.3', '0.9', '0.9.1', '0.9.2', '0.9.3', '0.9.4', '0.9.5', '0.9.6', '1.0.0', '1.0.0rc1', '1.0.1', '2.0.0', '2.0.0rc1', '2.0.0rc2', '2.0.0rc3', '2.0.0rc4', '2.0.0rc5', '2.0.1', '2.0.2', '2.0.3', '2.1.0', '2.1.1', '2.1.2', '2.2.0', '2.2.0a1', '2.2.1', '2.2.2'], 'database_specific': {'source': 'https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2023/02/GHSA-xg9f-g7g7-2323/GHSA-xg9f-g7g7-2323.json'}}], 'schema_version': '1.4.0', 'severity': [{'type': 'CVSS_V3', 'score': 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H'}]}]}
[2023-04-27 22:02:18,774-INFO-scanDependency-93]: Scanning whitenoise 6.2.0...
[2023-04-27 22:02:18,774-INFO-scanDependency-94]: {}
[2023-04-27 22:02:19,220-INFO-scanDependency-93]: Scanning zipp 3.8.0...
[2023-04-27 22:02:19,220-INFO-scanDependency-94]: {}
[2023-04-27 22:02:19,221-INFO-scanDependencies-127]: Completed scanning dependency vulnerabilities
[2023-04-27 22:02:19,221-INFO-scanDependencies-128]: Vulnerabilities found: 6
[2023-04-27 22:02:19,223-INFO-dependency-42]: Execution time: 17.39437961578369
[2023-04-27 22:02:19,223-INFO-dependency-43]: =============== Finished dependency detection ===============
